"""
Rule Engine Enums — Astrolife V2 Phase 5A
"""
from enum import Enum


class RuleCategory(str, Enum):
    YOGA = "YOGA"
    DOSHA = "DOSHA"
    JAIMINI = "JAIMINI"
    STRENGTH = "STRENGTH"
    DIGNITY = "DIGNITY"
    HOUSE = "HOUSE"
    LORDSHIP = "LORDSHIP"
    ASPECT = "ASPECT"
    TIMING = "TIMING"
    CUSTOM = "CUSTOM"


class RuleTradition(str, Enum):
    PARASHARI_CLASSICAL = "PARASHARI_CLASSICAL"
    JAIMINI = "JAIMINI"
    TRADITION_DEPENDENT = "TRADITION_DEPENDENT"
    WESTERN = "WESTERN"
    CUSTOM = "CUSTOM"


class RuleStatus(str, Enum):
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    DEPRECATED = "DEPRECATED"
    EXPERIMENTAL = "EXPERIMENTAL"


class FormationStatus(str, Enum):
    NOT_FORMED = "NOT_FORMED"
    FORMED = "FORMED"
    PARTIAL = "PARTIAL"
    UNCERTAIN = "UNCERTAIN"


class StrengthStatus(str, Enum):
    UNKNOWN = "UNKNOWN"
    WEAK = "WEAK"
    MODERATE = "MODERATE"
    STRONG = "STRONG"


class ActivationStatus(str, Enum):
    NOT_EVALUATED = "NOT_EVALUATED"
    INACTIVE = "INACTIVE"
    ACTIVE = "ACTIVE"
    PARTIALLY_ACTIVE = "PARTIALLY_ACTIVE"


class CancellationStatus(str, Enum):
    NONE = "NONE"
    PARTIAL = "PARTIAL"
    FULL = "FULL"


class MitigationStatus(str, Enum):
    NONE = "NONE"
    PARTIAL = "PARTIAL"
    SIGNIFICANT = "SIGNIFICANT"


class ConfidenceLevel(str, Enum):
    VERIFIED = "VERIFIED"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    TRADITION_DEPENDENT = "TRADITION_DEPENDENT"
    EXPERIMENTAL = "EXPERIMENTAL"
    CUSTOM = "CUSTOM"


class SourceType(str, Enum):
    CLASSICAL_TEXT = "CLASSICAL_TEXT"
    COMMENTARY = "COMMENTARY"
    MODERN_AUTHOR = "MODERN_AUTHOR"
    ORAL_TRADITION = "ORAL_TRADITION"
    UNVERIFIED = "UNVERIFIED"
    CUSTOM = "CUSTOM"


class EvidenceType(str, Enum):
    PLANET_IN_SIGN = "PLANET_IN_SIGN"
    PLANET_IN_HOUSE = "PLANET_IN_HOUSE"
    PLANET_IN_VARGA = "PLANET_IN_VARGA"
    PLANET_DIGNITY = "PLANET_DIGNITY"
    PLANET_STRENGTH = "PLANET_STRENGTH"
    PLANET_AVASTHA = "PLANET_AVASTHA"
    HOUSE_LORD_POSITION = "HOUSE_LORD_POSITION"
    LORDSHIP_RELATIONSHIP = "LORDSHIP_RELATIONSHIP"
    CONJUNCTION = "CONJUNCTION"
    ASPECT = "ASPECT"
    EXCHANGE = "EXCHANGE"
    KENDRA_TRIKONA = "KENDRA_TRIKONA"
    DUSTHANA = "DUSTHANA"
    MARAKA = "MARAKA"
    YOGAKARAKA = "YOGAKARAKA"
    FUNCTIONAL_NATURE = "FUNCTIONAL_NATURE"
    DASHA_PERIOD = "DASHA_PERIOD"
    TRANSIT = "TRANSIT"
    PANCHANGA = "PANCHANGA"
    VARGA_POSITION = "VARGA_POSITION"
    CUSTOM = "CUSTOM"


class LogicalOperator(str, Enum):
    AND = "AND"
    OR = "OR"
    NOT = "NOT"