"""
Phase 5H — Jaimini Event Candidate Model.

Deterministic structured models for event candidates generated by the
Jaimini Timing + Event-Candidate Engine. Zero prediction, zero AI,
zero outcome. All fields are deterministic and provenance-aware.

DO NOT add natural-language outcome fields. DO NOT add arbitrary scores.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Dict, List, Optional, Any

from pydantic import BaseModel, Field


# ============================================================================
# Event Category Model
# ============================================================================


class JaiminiEventCategory(str, Enum):
    """Controlled vocabulary of event categories. Labels for organizing
    rule activation. Do NOT guarantee outcomes."""

    RELATIONSHIP = "RELATIONSHIP"
    MARRIAGE = "MARRIAGE"
    CAREER = "CAREER"
    EDUCATION = "EDUCATION"
    WEALTH = "WEALTH"
    PROPERTY = "PROPERTY"
    CHILDREN = "CHILDREN"
    SPIRITUAL = "SPIRITUAL"
    TRAVEL = "TRAVEL"
    HEALTH = "HEALTH"
    GENERAL_LIFE_CHANGE = "GENERAL_LIFE_CHANGE"
    FAMILY = "FAMILY"


# ============================================================================
# Precision Model
# ============================================================================


class TemporalPrecision(str, Enum):
    """Precision metadata for candidate windows. Derived from evidence,
    not fabricated."""

    EXACT = "EXACT"
    DAY = "DAY"
    WINDOW = "WINDOW"
    APPROXIMATE = "APPROXIMATE"
    UNKNOWN = "UNKNOWN"


# ============================================================================
# Convergence Model
# ============================================================================


class ConvergenceLevel(str, Enum):
    """Structural convergence labels. NOT probability."""

    SINGLE_CONDITION = "SINGLE_CONDITION"
    DOUBLE_CONDITION = "DOUBLE_CONDITION"
    MULTI_CONDITION = "MULTI_CONDITION"


# ============================================================================
# Conflict Model (reuse Phase 5F classes where possible)
# ============================================================================


class ConflictType(str, Enum):
    """Conflict types reused from Phase 5F infrastructure."""

    DIRECT_CONTRADICTION = "DIRECT_CONTRADICTION"
    APPARENT_CONTRADICTION = "APPARENT_CONTRADICTION"
    DIFFERENT_DIMENSIONS = "DIFFERENT_DIMENSIONS"
    TRADITION_VARIANT = "TRADITION_VARIANT"
    INSUFFICIENT_INFORMATION = "INSUFFICIENT_INFORMATION"


# ============================================================================
# JaiminiEventCandidate — Core Model
# ============================================================================


class JaiminiEventCandidate(BaseModel):
    """Immutable structured model for a Jaimini event candidate.

    The output is NOT a prediction. It is:

    "These deterministic astrological conditions are simultaneously
    active during this time window."

    The downstream prediction/AI layer will later interpret those candidates.
    """

    candidate_id: str = Field(
        description="Deterministic ID: {profile}:{category}:{start_iso}:{end_iso}"
    )
    event_category: JaiminiEventCategory = Field(description="Organizing label only")
    rule_ids: List[str] = Field(
        default_factory=list,
        description="Rule IDs that activated this candidate",
    )
    dasha_period_ids: List[str] = Field(
        default_factory=list,
        description="Dasha period IDs active during this window",
    )
    transit_condition_ids: List[str] = Field(
        default_factory=list,
        description="Transit condition IDs active during this window",
    )
    start: datetime = Field(
        description="Candidate start (UTC, ISO, tz-aware)"
    )
    end: datetime = Field(
        description="Candidate end (UTC, ISO, tz-aware); half-open [start, end)"
    )
    peak: Optional[datetime] = Field(
        default=None,
        description="Exact event timestamp where mathematically defined;"
        " UNKNOWN if only a window is supported",
    )
    duration_years: float = Field(
        description="Candidate duration in years (from evidence, not fabricated precision)"
    )
    duration_precision: TemporalPrecision = Field(
        description="Precision: EXACT/DAY/WINDOW/APPROXIMATE/UNKNOWN"
    )
    status: str = Field(
        default="ACTIVE",
        description="Candidate status: ACTIVE, SATISFIED, EXPIRED",
    )
    profile: str = Field(
        description="Exact Jaimini Dasha profile ID used",
    )
    evidence: List[str] = Field(
        default_factory=list,
        description="Traceable evidence paths from canonical facts",
    )
    dependencies: List[str] = Field(
        default_factory=list,
        description="Explicit dependency IDs (no circular, no missing)",
    )
    conflicts: List[str] = Field(
        default_factory=list,
        description="Conflict type IDs (from Phase 5F infrastructure)",
    )
    provenance: str = Field(
        default="TRADITION_DEPENDENT",
        description="Source confidence: never upgraded by engine",
    )
    confidence: str = Field(
        default="TRADITION_DEPENDENT",
        description="Never arbitrary; always TRADITION_DEPENDENT or UNKNOWN",
    )
    convergence: str = Field(
        default="SINGLE_CONDITION",
        description="Structural convergence label: SINGLE/Double/MULTI",
    )
    tradition: str = Field(
        default="JAIMINI",
        description="Tradition label from event mapping catalogue",
    )
    method: str = Field(
        default="",
        description="Method from event mapping catalogue",
    )
    source_reference: str = Field(
        default="UNVERIFIED",
        description="Never upgraded from UNVERIFIED by engine",
    )

    # Model enforcement: no outcome field, no outcome-intended field

    model_config = {"frozen": True}  # immutable after construction

    def __repr__(self) -> str:
        return f"<JaiminiEventCandidate {self.candidate_id} " \
               f"cat={self.event_category} prof={self.profile} " \
               f"[{self.start} → {self.end}] prec={self.duration_precision}>"


# ============================================================================
# JaiminiTimingEvaluation — Evaluation Container
# ============================================================================


class JaiminiTimingEvaluation(BaseModel):
    """Container for a complete Jaimini timing evaluation.

    Holds candidates, conflicts, evidence, dependencies, provenance,
    and the evaluation range. Deterministic: sorted orderings, no
    timestamps hidden in IDs.
    """

    profile: str = Field(default="", description="Jaimini Dasha profile ID")
    candidates: List[JaiminiEventCandidate] = Field(
        default_factory=list,
        description="Generated event candidates, sorted by deterministic criteria",
    )
    conflicts: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Reported conflicts, not resolved",
    )
    evidence: Dict[str, Any] = Field(
        default_factory=dict,
        description="Traceable evidence graph references",
    )
    dependencies: List[str] = Field(
        default_factory=list,
        description="Explicit dependency IDs validated",
    )
    validation: Dict[str, Any] = Field(
        default_factory=dict,
        description="Validation results: no circular deps, etc.",
    )
    provenance: Dict[str, Any] = Field(
        default_factory=dict,
        description="Provenance metadata: tradition, method, source_reference",
    )
    evaluation_range: Dict[str, str] = Field(
        default_factory=dict,
        description="{evaluation_start, evaluation_end} inputs",
    )
    total_candidates: int = Field(default=0, description="Count of candidates")
    generated_at: str = Field(
        default="",
        description="ISO timestamp at evaluation generation (API boundary only)",
    )

    model_config = {"frozen": True}


# ============================================================================
# Dasha Activation Data
# ============================================================================


class DashaActivation(BaseModel):
    """Records dasha activation details for every candidate.

    Every candidate must record these fields.
    """

    dasha_system: str = Field(description="Dasha system: JAIMINI_CHARA")
    profile_id: str = Field(description="Exact profile ID used")
    dasha_level: str = Field(description="MAHA_DASHA or ANTARDASHA")
    active_sign: str = Field(description="Currently active dasha sign")
    dasha_start: datetime = Field(description="Dasha period start (UTC ISO)")
    dasha_end: datetime = Field(description="Dasha period end (UTC ISO)")


# ============================================================================
# Mapping Entry — Rule → Event Catalogue
# ============================================================================


class MappingEntry(BaseModel):
    """Explicit rule-to-event mapping definition. Every mapping must
    defensibly define all activation conditions."""

    rule_id: str = Field(description="Jaimini rule ID (e.g. JAI.KARAKA.AK_AMK_CONJUNCTION)")
    event_category: JaiminiEventCategory = Field(description="Event category label")
    activation_conditions: List[str] = Field(
        description="What must be active: active_dasha_sign, transit_relationship, etc."
    )
    timing_requirements: str = Field(
        description="Dasha level required: MAHA_DASHA, ANTARDASHA, etc."
    )
    required_dasha_level: str = Field(
        description="Minimum dasha level for activation"
    )
    transit_requirements: str = Field(
        description="Transit condition(s) required, or EMPTY for none"
    )
    evidence_requirements: List[str] = Field(
        description="Evidence tiers required from graph"
    )
    tradition: str = Field(description="Tradition label")
    method: str = Field(description="Method/Profile ID from catalogue")
    confidence: str = Field(description="Confidence: TRADITION_DEPENDENT or UNKNOWN")
    provenance: str = Field(default="UNVERIFIED", description="Source reference status")
    source_reference: str = Field(default="UNVERIFIED", description="Explicit source reference")

    # Derived during candidate generation
    activated: bool = Field(default=False, description="Whether this mapping activated")
    convergence_level: str = Field(
        default="SINGLE_CONDITION",
        description="Structural convergence level",
    )