"""
Astrolife V2 — Dynamic Rules Core Module.

Phase 6A: Dynamic Rule Knowledge Specification (declarative DSL, schema, validation, security).
Phase 6B: Canonical Fact Resolution & Dynamic Evaluation Engine (facts, bindings, tradition isolation).
Phase 6C: Developer Rule Lab / Rule Management Backend (lifecycle, testing, reviews, activation, diffs, audit).
Phase 6D: Rule Knowledge, Evidence & Provenance Integration (claims, evidence records, bundles, verification, graphs).
"""
from __future__ import annotations

from .schema import (
    SCHEMA_VERSION,
    RuleIdentity,
    RuleClassification,
    SourceReference,
    RuleProvenance,
    ConditionNode,
    RuleSemantics,
    RuleDependencies,
    RuleEvidenceSpec,
    RuleLifecycle,
    RuleValidationInfo,
    DynamicRuleDefinition,
)
from .dsl import (
    LOGICAL_OPS,
    PRIMITIVES,
    SUSPICIOUS_PATTERNS,
    find_suspicious_text,
    known_ops,
)
from .evaluator import (
    MISSING,
    TRUE,
    FALSE,
    UNKNOWN,
    EvidenceItem,
    TreeOutcome,
    DynamicRuleOutcome,
    evaluate_tree,
    evaluate_rule,
)
from .validators import (
    Diagnostic,
    FIREWALL,
    validate_rule,
    compare_versions,
)
from .registry import (
    DuplicateVersionError,
    DynamicRuleRegistry,
)
from .serialization import (
    to_canonical_json,
    from_canonical_json,
    round_trip,
)
from .namespace import (
    match_namespace,
    namespace_of,
    list_namespaces,
)
from .context import (
    DynamicEvaluationContext,
    build_context,
)
from .resolver import (
    RESOLVED,
    MISSING,
    INVALID,
    UNAVAILABLE,
    FactResolution,
    CanonicalFactResolver,
)
from .bindings import (
    PRIMITIVE_BINDINGS,
    required_paths,
)
from .results import DynamicRuleResult
from .engine import (
    evaluate_dynamic_rule,
    evaluate_dynamic_rule_by_id,
    evaluate_many,
    audit_dynamic_rule_evaluation,
)

# ——— Phase 6C Additions ———
from .lifecycle import (
    LIFECYCLE_STATES,
    LEGAL_TRANSITIONS,
    is_valid_transition,
    validate_transition,
    LifecycleTransitionError,
    RuleLifecycleStateMachine,
)
from .rule_package import (
    RulePackage,
    RuleTestCase,
    RuleTestReport,
    ValidationReport,
    ActivationReport,
    PackageFingerprint,
    RuleHealth,
    RuleDiff,
    RuleDiffCategory,
    create_rule_draft,
)
from .test_fixture import (
    RuleTestExecutor,
    run_rule_tests,
)
from .activation import (
    activate_rule,
    disable_rule,
    deprecate_rule,
    archive_rule,
)
from .catalogue import (
    list_rules,
    get_rule,
    get_version,
    list_versions,
    search_rules,
    filter_by_tradition,
    filter_by_category,
    filter_by_status,
    filter_by_provenance,
    filter_by_validation_status,
)
from .source import (
    SourceManagement,
    SourceRecord,
    PRIMARY,
    SECONDARY,
    SUPPORTING,
    CONFLICTING,
    ALL_SOURCE_STATUSES,
    VERIFIED,
    UNVERIFIED,
    CONTESTED,
    SECONDARY_STATUS,
    TRADITIONAL,
    USER_SUPPLIED,
    CUSTOM_STATUS,
)
from .review import (
    RuleReviewRecord,
    ReviewOutcome,
    ReviewWorkflow,
    create_review_record,
    REVIEW_DECISIONS,
)
from .audit import (
    AuditRecord,
    AuditLog,
    AUDIT_EVENT_TYPES,
)
from .fingerprint import (
    compute_fingerprint,
    fingerprints_match,
    fingerprint_from_dict,
)
from .diff import (
    compare_rule_versions,
)
from .import_export import (
    export_package,
    import_package,
    export,
    import_,
    ExportResult,
    ImportResult,
)
from .preview import (
    DependencyPreview,
    EvidencePreview,
    EvidenceChainItem,
    DerivedFactChainItem,
    preview_rule_dependencies,
    preview_rule_evidence,
)
from .service import (
    RuleLabService,
)

# ——— Phase 6D Additions ———
from .claim import (
    ClaimRecord,
    ClaimRegistry,
)
from .evidence_record import (
    EvidenceRecord,
    EvidenceBundle,
)
from .verification import (
    SourceVerificationPolicy,
    SourceVerificationResult,
    verify_source,
    verify_source_management,
    validate_verification_transition,
    DEFAULT_VERIFICATION_POLICY,
)
from .evidence_graph import (
    EvidenceGraph,
    GraphNode,
    GraphEdge,
    DIRECT_FACT,
    DERIVED_FACT,
    RULE_DERIVED,
    SOURCE_CLAIM,
    DERIVES,
    FEEDS,
    EVALUATES_TO,
    CO_CHART_FACT,
    SUPPORTS,
    CONTRADICTS,
    TRACKED_SEPARATELY,
    build_evidence_graph_from_bundle,
    trace_evaluation,
)

# ——— Phase 6E Additions (additive only; no existing symbol changed) ———
from .knowledge import (
    RULE_SYSTEMS,
    TRADITIONS,
    QUERY_TRADITIONS,
    CATEGORIES,
    APPLICABLE,
    NOT_APPLICABLE,
    UNKNOWN,
    INVALID,
    REASONS,
    DISCOVERY_MODES,
    RuleApplicabilitySpec,
    RuleKnowledgeEntry,
    KnowledgeContext,
    ApplicabilityReason,
    RuleApplicabilityResult,
    KnowledgeConflict,
    RuleKnowledgeCatalogue,
    RuleKnowledgeHealth,
    KnowledgeGraph,
    CatalogueSnapshot,
    normalize_tradition,
    normalize_system,
    normalize_category,
    derive_spec_from_definition,
    entry_from_dynamic_definition,
    evaluate_rule_applicability,
    get_rule_health,
    build_knowledge_graph,
    build_snapshot,
    snapshot_round_trip,
    build_golden_catalogue,
    build_custom_fixtures,
    get_rule_catalogue,
    find_rules,
    get_rule,
    get_rule_version,
    find_rules_for_context,
    find_rules_by_fact,
    find_rules_by_varga,
    find_rules_by_dasha,
    find_rules_by_transit,
    find_rules_by_strength,
    find_rules_by_jaimini_dependency,
    find_rules_by_source,
    find_conflicts,
    get_catalogue_snapshot,
    measure_performance,
)

__all__ = [
    # Phase 6A
    "SCHEMA_VERSION",
    "RuleIdentity",
    "RuleClassification",
    "SourceReference",
    "RuleProvenance",
    "ConditionNode",
    "RuleSemantics",
    "RuleDependencies",
    "RuleEvidenceSpec",
    "RuleLifecycle",
    "RuleValidationInfo",
    "DynamicRuleDefinition",
    "LOGICAL_OPS",
    "PRIMITIVES",
    "SUSPICIOUS_PATTERNS",
    "find_suspicious_text",
    "known_ops",
    "MISSING",
    "TRUE",
    "FALSE",
    "UNKNOWN",
    "EvidenceItem",
    "TreeOutcome",
    "DynamicRuleOutcome",
    "evaluate_tree",
    "evaluate_rule",
    "Diagnostic",
    "FIREWALL",
    "validate_rule",
    "compare_versions",
    "DuplicateVersionError",
    "DynamicRuleRegistry",
    "to_canonical_json",
    "from_canonical_json",
    "round_trip",
    # Phase 6B
    "match_namespace",
    "namespace_of",
    "list_namespaces",
    "DynamicEvaluationContext",
    "build_context",
    "RESOLVED",
    "INVALID",
    "UNAVAILABLE",
    "FactResolution",
    "CanonicalFactResolver",
    "PRIMITIVE_BINDINGS",
    "required_paths",
    "DynamicRuleResult",
    "evaluate_dynamic_rule",
    "evaluate_dynamic_rule_by_id",
    "evaluate_many",
    "audit_dynamic_rule_evaluation",
    # Phase 6C
    "LIFECYCLE_STATES",
    "LEGAL_TRANSITIONS",
    "is_valid_transition",
    "validate_transition",
    "LifecycleTransitionError",
    "RuleLifecycleStateMachine",
    "RulePackage",
    "RuleTestCase",
    "RuleTestReport",
    "ValidationReport",
    "ActivationReport",
    "PackageFingerprint",
    "RuleHealth",
    "RuleDiff",
    "RuleDiffCategory",
    "create_rule_draft",
    "RuleTestExecutor",
    "run_rule_tests",
    "activate_rule",
    "disable_rule",
    "deprecate_rule",
    "archive_rule",
    "list_rules",
    "get_rule",
    "get_version",
    "list_versions",
    "search_rules",
    "filter_by_tradition",
    "filter_by_category",
    "filter_by_status",
    "filter_by_provenance",
    "filter_by_validation_status",
    "SourceManagement",
    "SourceRecord",
    "PRIMARY",
    "SECONDARY",
    "SUPPORTING",
    "CONFLICTING",
    "ALL_SOURCE_STATUSES",
    "RuleReviewRecord",
    "ReviewOutcome",
    "ReviewWorkflow",
    "create_review_record",
    "REVIEW_DECISIONS",
    "AuditRecord",
    "AuditLog",
    "AUDIT_EVENT_TYPES",
    "compute_fingerprint",
    "fingerprints_match",
    "fingerprint_from_dict",
    "compare_rule_versions",
    "export_package",
    "import_package",
    "export",
    "import_",
    "ExportResult",
    "ImportResult",
    "DependencyPreview",
    "EvidencePreview",
    "EvidenceChainItem",
    "DerivedFactChainItem",
    "preview_rule_dependencies",
    "preview_rule_evidence",
    "RuleLabService",

    # Phase 6D
    "ClaimRecord",
    "ClaimRegistry",
    "EvidenceRecord",
    "EvidenceBundle",
    "SourceVerificationPolicy",
    "SourceVerificationResult",
    "verify_source",
    "verify_source_management",
    "validate_verification_transition",
    "DEFAULT_VERIFICATION_POLICY",
    "EvidenceGraph",
    "GraphNode",
    "GraphEdge",
    "DIRECT_FACT",
    "DERIVED_FACT",
    "RULE_DERIVED",
    "SOURCE_CLAIM",
    "DERIVES",
    "FEEDS",
    "EVALUATES_TO",
    "CO_CHART_FACT",
    "SUPPORTS",
    "CONTRADICTS",
    "TRACKED_SEPARATELY",
    "build_evidence_graph_from_bundle",
    "trace_evaluation",

    # Phase 6E
    "RULE_SYSTEMS",
    "TRADITIONS",
    "QUERY_TRADITIONS",
    "CATEGORIES",
    "APPLICABLE",
    "NOT_APPLICABLE",
    "UNKNOWN",
    "INVALID",
    "REASONS",
    "DISCOVERY_MODES",
    "RuleApplicabilitySpec",
    "RuleKnowledgeEntry",
    "KnowledgeContext",
    "ApplicabilityReason",
    "RuleApplicabilityResult",
    "KnowledgeConflict",
    "RuleKnowledgeCatalogue",
    "RuleKnowledgeHealth",
    "KnowledgeGraph",
    "CatalogueSnapshot",
    "normalize_tradition",
    "normalize_system",
    "normalize_category",
    "derive_spec_from_definition",
    "entry_from_dynamic_definition",
    "evaluate_rule_applicability",
    "get_rule_health",
    "build_knowledge_graph",
    "build_snapshot",
    "snapshot_round_trip",
    "build_golden_catalogue",
    "build_custom_fixtures",
    "get_rule_catalogue",
    "find_rules",
    "get_rule",
    "get_rule_version",
    "find_rules_for_context",
    "find_rules_by_fact",
    "find_rules_by_varga",
    "find_rules_by_dasha",
    "find_rules_by_transit",
    "find_rules_by_strength",
    "find_rules_by_jaimini_dependency",
    "find_rules_by_source",
    "find_conflicts",
    "get_catalogue_snapshot",
    "measure_performance",
]